version: '3'

services:
  backend:
    image: neper:backend
    build:
      context: ./backend/
      dockerfile: ./docker/prod/Dockerfile
    container_name: backend
    ports:
      - 80:8080
