version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/app:/app
    ports:
      - 80:80
    depends_on:
      - test
  test:
    build: ./backend
    container_name: test
    volumes:
      - ./backend/app:/app
    command: pytest
