version: '3'

services:
  backend:
    image: neper:backend
    build:
      context: ./backend/
      dockerfile: ./docker/dev/Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
