version: '3'

services:
  auction:
    image: auction:backend
    build:
      context: ./backend/
      dockerfile: ./docker/prod/Dockerfile
    container_name: backend
    ports:
      - 80:8080
    environment:
      - PORT=8080
      - VARIABLE_NAME=api
