version: '3'

services:
  auction:
    image: auction:backend
    build:
      context: ./backend/
      dockerfile: ./docker/prod/Dockerfile
    container_name: backend
    volumes:
      - ./storage/:/app/storage/db
    ports:
      - 80:80
